apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  namespace: akv2k8s
  name: akv2k8s
spec:
  chart:
    spec:
      chart: akv2k8s
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: spv-charts
  interval: 1m0s
  targetNamespace: akv2k8s